"""empty message

Revision ID: 369968ac19a1
Revises: 9afe11c0e1dd
Create Date: 2023-04-27 10:42:26.841317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '369968ac19a1'
down_revision = '9afe11c0e1dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
