"""empty message

Revision ID: 6e6776fa8376
Revises: 369968ac19a1
Create Date: 2023-04-28 15:10:45.908898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e6776fa8376'
down_revision = '369968ac19a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diary', schema=None) as batch_op:
        batch_op.drop_constraint('fk_question_user_id_user', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_diary_user_id_user'), 'user', ['user_id'], ['id'], ondelete='NO ACTION')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('nickname',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('nickname',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('diary', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_diary_user_id_user'), type_='foreignkey')
        batch_op.create_foreign_key('fk_question_user_id_user', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
