"""empty message

Revision ID: 72debbb7a267
Revises: 6e6776fa8376
Create Date: 2023-04-28 15:26:57.871589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72debbb7a267'
down_revision = '6e6776fa8376'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diary', schema=None) as batch_op:
        batch_op.drop_constraint('fk_diary_user_id_user', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_diary_user_id_user'), 'user', ['user_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diary', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_diary_user_id_user'), type_='foreignkey')
        batch_op.create_foreign_key('fk_diary_user_id_user', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
