"""empty message

Revision ID: 9afe11c0e1dd
Revises: 677a4e9b4ee6
Create Date: 2023-04-26 17:27:26.689814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9afe11c0e1dd'
down_revision = '677a4e9b4ee6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sentence')
    with op.batch_alter_table('diary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vote_count', sa.Integer(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_user_id_user', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_user_user_id_user', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('diary', schema=None) as batch_op:
        batch_op.drop_column('vote_count')

    op.create_table('sentence',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sentence1', sa.TEXT(), nullable=False),
    sa.Column('sentence2', sa.TEXT(), nullable=False),
    sa.Column('sentence3', sa.TEXT(), nullable=False),
    sa.Column('sentence4', sa.TEXT(), nullable=False),
    sa.Column('sentence5', sa.TEXT(), nullable=False),
    sa.Column('sentence6', sa.TEXT(), nullable=False),
    sa.Column('sentence7', sa.TEXT(), nullable=False),
    sa.Column('sentence8', sa.TEXT(), nullable=False),
    sa.Column('sentence9', sa.TEXT(), nullable=False),
    sa.Column('sentence10', sa.TEXT(), nullable=False),
    sa.Column('sentence11', sa.TEXT(), nullable=False),
    sa.Column('sentence12', sa.TEXT(), nullable=False),
    sa.Column('sentence13', sa.TEXT(), nullable=False),
    sa.Column('sentence14', sa.TEXT(), nullable=False),
    sa.Column('sentence15', sa.TEXT(), nullable=False),
    sa.Column('sentence16', sa.TEXT(), nullable=False),
    sa.Column('sentence17', sa.TEXT(), nullable=False),
    sa.Column('sentence18', sa.TEXT(), nullable=False),
    sa.Column('sentence19', sa.TEXT(), nullable=False),
    sa.Column('sentence20', sa.TEXT(), nullable=False),
    sa.Column('sentence21', sa.TEXT(), nullable=False),
    sa.Column('sentence22', sa.TEXT(), nullable=False),
    sa.Column('sentence23', sa.TEXT(), nullable=False),
    sa.Column('sentence24', sa.TEXT(), nullable=False),
    sa.Column('sentence25', sa.TEXT(), nullable=False),
    sa.Column('sentence26', sa.TEXT(), nullable=False),
    sa.Column('sentence27', sa.TEXT(), nullable=False),
    sa.Column('sentence28', sa.TEXT(), nullable=False),
    sa.Column('sentence29', sa.TEXT(), nullable=False),
    sa.Column('sentence30', sa.TEXT(), nullable=False),
    sa.Column('sentence31', sa.TEXT(), nullable=False),
    sa.Column('sentence32', sa.TEXT(), nullable=False),
    sa.Column('sentence33', sa.TEXT(), nullable=False),
    sa.Column('sentence34', sa.TEXT(), nullable=False),
    sa.Column('sentence35', sa.TEXT(), nullable=False),
    sa.Column('sentence36', sa.TEXT(), nullable=False),
    sa.Column('sentence37', sa.TEXT(), nullable=False),
    sa.Column('sentence38', sa.TEXT(), nullable=False),
    sa.Column('sentence39', sa.TEXT(), nullable=False),
    sa.Column('sentence40', sa.TEXT(), nullable=False),
    sa.Column('sentence41', sa.TEXT(), nullable=False),
    sa.Column('sentence42', sa.TEXT(), nullable=False),
    sa.Column('sentence43', sa.TEXT(), nullable=False),
    sa.Column('sentence44', sa.TEXT(), nullable=False),
    sa.Column('sentence45', sa.TEXT(), nullable=False),
    sa.Column('sentence46', sa.TEXT(), nullable=False),
    sa.Column('sentence47', sa.TEXT(), nullable=False),
    sa.Column('sentence48', sa.TEXT(), nullable=False),
    sa.Column('sentence49', sa.TEXT(), nullable=False),
    sa.Column('sentence50', sa.TEXT(), nullable=False),
    sa.Column('sentence51', sa.TEXT(), nullable=False),
    sa.Column('sentence52', sa.TEXT(), nullable=False),
    sa.Column('sentence53', sa.TEXT(), nullable=False),
    sa.Column('sentence54', sa.TEXT(), nullable=False),
    sa.Column('sentence55', sa.TEXT(), nullable=False),
    sa.Column('sentence56', sa.TEXT(), nullable=False),
    sa.Column('sentence57', sa.TEXT(), nullable=False),
    sa.Column('sentence58', sa.TEXT(), nullable=False),
    sa.Column('sentence59', sa.TEXT(), nullable=False),
    sa.Column('sentence60', sa.TEXT(), nullable=False),
    sa.Column('sentence61', sa.TEXT(), nullable=False),
    sa.Column('sentence62', sa.TEXT(), nullable=False),
    sa.Column('sentence63', sa.TEXT(), nullable=False),
    sa.Column('sentence64', sa.TEXT(), nullable=False),
    sa.Column('sentence65', sa.TEXT(), nullable=False),
    sa.Column('sentence66', sa.TEXT(), nullable=False),
    sa.Column('sentence67', sa.TEXT(), nullable=False),
    sa.Column('sentence68', sa.TEXT(), nullable=False),
    sa.Column('sentence69', sa.TEXT(), nullable=False),
    sa.Column('sentence70', sa.TEXT(), nullable=False),
    sa.Column('sentence71', sa.TEXT(), nullable=False),
    sa.Column('sentence72', sa.TEXT(), nullable=False),
    sa.Column('sentence73', sa.TEXT(), nullable=False),
    sa.Column('sentence74', sa.TEXT(), nullable=False),
    sa.Column('sentence75', sa.TEXT(), nullable=False),
    sa.Column('sentence76', sa.TEXT(), nullable=False),
    sa.Column('sentence77', sa.TEXT(), nullable=False),
    sa.Column('sentence78', sa.TEXT(), nullable=False),
    sa.Column('sentence79', sa.TEXT(), nullable=False),
    sa.Column('sentence80', sa.TEXT(), nullable=False),
    sa.Column('sentence81', sa.TEXT(), nullable=False),
    sa.Column('sentence82', sa.TEXT(), nullable=False),
    sa.Column('sentence83', sa.TEXT(), nullable=False),
    sa.Column('sentence84', sa.TEXT(), nullable=False),
    sa.Column('sentence85', sa.TEXT(), nullable=False),
    sa.Column('sentence86', sa.TEXT(), nullable=False),
    sa.Column('sentence87', sa.TEXT(), nullable=False),
    sa.Column('sentence88', sa.TEXT(), nullable=False),
    sa.Column('sentence89', sa.TEXT(), nullable=False),
    sa.Column('sentence90', sa.TEXT(), nullable=False),
    sa.Column('sentence91', sa.TEXT(), nullable=False),
    sa.Column('sentence92', sa.TEXT(), nullable=False),
    sa.Column('sentence93', sa.TEXT(), nullable=False),
    sa.Column('sentence94', sa.TEXT(), nullable=False),
    sa.Column('sentence95', sa.TEXT(), nullable=False),
    sa.Column('sentence96', sa.TEXT(), nullable=False),
    sa.Column('sentence97', sa.TEXT(), nullable=False),
    sa.Column('sentence98', sa.TEXT(), nullable=False),
    sa.Column('sentence99', sa.TEXT(), nullable=False),
    sa.Column('sentence100', sa.TEXT(), nullable=False),
    sa.Column('sentence101', sa.TEXT(), nullable=False),
    sa.Column('sentence102', sa.TEXT(), nullable=False),
    sa.Column('sentence103', sa.TEXT(), nullable=False),
    sa.Column('sentence104', sa.TEXT(), nullable=False),
    sa.Column('sentence105', sa.TEXT(), nullable=False),
    sa.Column('sentence106', sa.TEXT(), nullable=False),
    sa.Column('sentence107', sa.TEXT(), nullable=False),
    sa.Column('sentence108', sa.TEXT(), nullable=False),
    sa.Column('sentence109', sa.TEXT(), nullable=False),
    sa.Column('sentence110', sa.TEXT(), nullable=False),
    sa.Column('sentence111', sa.TEXT(), nullable=False),
    sa.Column('sentence112', sa.TEXT(), nullable=False),
    sa.Column('sentence113', sa.TEXT(), nullable=False),
    sa.Column('sentence114', sa.TEXT(), nullable=False),
    sa.Column('sentence115', sa.TEXT(), nullable=False),
    sa.Column('sentence116', sa.TEXT(), nullable=False),
    sa.Column('sentence117', sa.TEXT(), nullable=False),
    sa.Column('sentence118', sa.TEXT(), nullable=False),
    sa.Column('sentence119', sa.TEXT(), nullable=False),
    sa.Column('sentence120', sa.TEXT(), nullable=False),
    sa.Column('sentence121', sa.TEXT(), nullable=False),
    sa.Column('sentence122', sa.TEXT(), nullable=False),
    sa.Column('sentence123', sa.TEXT(), nullable=False),
    sa.Column('sentence124', sa.TEXT(), nullable=False),
    sa.Column('sentence125', sa.TEXT(), nullable=False),
    sa.Column('sentence126', sa.TEXT(), nullable=False),
    sa.Column('sentence127', sa.TEXT(), nullable=False),
    sa.Column('sentence128', sa.TEXT(), nullable=False),
    sa.Column('sentence129', sa.TEXT(), nullable=False),
    sa.Column('sentence130', sa.TEXT(), nullable=False),
    sa.Column('sentence131', sa.TEXT(), nullable=False),
    sa.Column('sentence132', sa.TEXT(), nullable=False),
    sa.Column('sentence133', sa.TEXT(), nullable=False),
    sa.Column('sentence134', sa.TEXT(), nullable=False),
    sa.Column('sentence135', sa.TEXT(), nullable=False),
    sa.Column('sentence136', sa.TEXT(), nullable=False),
    sa.Column('sentence137', sa.TEXT(), nullable=False),
    sa.Column('sentence138', sa.TEXT(), nullable=False),
    sa.Column('sentence139', sa.TEXT(), nullable=False),
    sa.Column('sentence140', sa.TEXT(), nullable=False),
    sa.Column('sentence141', sa.TEXT(), nullable=False),
    sa.Column('sentence142', sa.TEXT(), nullable=False),
    sa.Column('sentence143', sa.TEXT(), nullable=False),
    sa.Column('sentence144', sa.TEXT(), nullable=False),
    sa.Column('sentence145', sa.TEXT(), nullable=False),
    sa.Column('sentence146', sa.TEXT(), nullable=False),
    sa.Column('sentence147', sa.TEXT(), nullable=False),
    sa.Column('sentence148', sa.TEXT(), nullable=False),
    sa.Column('sentence149', sa.TEXT(), nullable=False),
    sa.Column('sentence150', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
